# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set workdir
WORKDIR /app

# Copy project files
COPY pyproject.toml uv.lock README.md ./
COPY main.py ./

# Install dependencies
RUN pip install --no-cache-dir pip>=22 && \
    pip install --no-cache-dir .

# Default command
CMD ["python", "main.py"]
